### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#101]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/Program.cs#L46

Ici il y a un problème avec ta boucle. Ta condition de sortie c'est si tu trouve le label ou si le label == null.
Que se passe t-il si ton label n'existe pas ?

**Comment by emilieDelsol** [comment]
j'aurai dû lire toutes les issues avant de corriger... Je butte sur une erreur dans cette méthode depuis tout à l'heure.. J'ai modifié par == null, ça ne plante plus  ^^ 
Par contre si le label n'existe pas le programme lève une exeption, il faut que je gère cette erreur.. ^^

**Comment by cegerard** [comment]
En effet. Tu dois éviter d'avoir une exception. Une exception n'est pas un comportement normal. Ici ta condition de boucle doit pouvoir gérer son arrêt.

Tu as deux cas à gérer. Le premier c'est quand tu trouves le label. Le deuxième c'est quand tu atteints la fin de la liste.

Pour le label c'est ok mais ta condition de fin de boucle n'est pas bonne. De plus dans un while la condition détermine l'entrée dans la boucle pas l'inverse.

Je peux te dire sans le lancer que ton code ne fonctionne pas. Tu as des cas de boucles infinies et en sortie ton code ne gère pas correctement le fait de savoir si tu as trouvé le label ou non.

Je te conseil de tester ton code au moins dans ta tête. Avec plusieurs cas:
- Liste vide (ici ton code va produire pleins d'erreurs)
- Liste avec un élément mais pas la label cherché
- Liste avec un élément et le label cherché
- Liste avec plusieurs éléments sans le label
- liste avec plusieurs éléments avec le label cherché
