### ISSUE TITLE
path

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#102]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/Program.cs#L68

Attention ton chemin ici est absolu. Il ne fonctionne que sur ton ordi.
Il faut faire attention quand tu partages du code que celui puisse être utilisé par tous.
Dans le cas des paths il faut garder des chemins relatifs.

**Comment by emilieDelsol** [comment]
j'ai modifié en mettant ../../1K.json, en mettant ~1K.json, il ne renvoit pas le bon chemin..

**Comment by cegerard** [comment]
ok
