### ISSUE TITLE
condition de boucle

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#2]
https://github.com/emilieDelsol/MentoratD2velop/blob/ed72dfe1e2c67bc7201c01a0b7e5883c49ef6826/searchJson/script.js#L7

Ton if ici peut être supprimé.
Tu peux utiliser une boucle while au lieu d'un for et avoir comme condition la taille de ton tableau et la recherche.
En règle générale quand tu as un condition d'arrêt sur une boucle n'utilse pas un for mais un while.

**Comment by emilieDelsol** [comment]
Je vais pousser le nouveau code, voilà la solution que j'ai écrit:

`let index =0;`
    `while(data[index].label!=searchLabel&&i<data.length)`
    `{`
        `index++;`
    `}`
    `if(index<=data.length)`
    `{`
        `console.log("the first object with label="+searchLabel+" is:");`
        `console.log(data[index]);`
        `resultSearchLabelId.textContent='the first object with label "' + searchLabel+ '" is: '+ JSON.stringify(data[index]) ;`
    `}`
