### ISSUE TITLE
reverse

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#23]
https://github.com/emilieDelsol/MentoratD2velop/blob/d1145d8a05b645a7897d05ff4cea0686aa64edcb/searchJson/script.js#L45

Pourquoi tu fais ça ?

**Comment by emilieDelsol** [comment]
parce que je dois sélectionner le dernier élément à partir de l'attribut weight, j'inverse le tableau ainsi le premier élément ayant l'attribut weight demandé correspond au dernier du tableau non inversé.

**Comment by cegerard** [comment]
Ok je comprends l'idée. Et tu saurais évaluer la complexité de l'algorithme du coup ? En faisant ça et en ne le faisant pas.

**Comment by cegerard** [comment]
Ce que je veux te faire remarquer c'est que ton inversion de tableau te coûte un parcours complet avec récriture totale du tableau. Tout ça pour ensuite le reparcourir une fois afin de trouver l'élément rechercher. Dans le pire de cas, il n'existe pas ou se trouve tout à la fin. Dans le meilleur des cas, c'est le premier élément et du coup tu ne fais qu'un parcours.

Alors qu'avec un parcours simple tu dois forcément parcourir tout le tableau. Du coup, pire cas = meilleur cas = un parcours total.

Tu as donc une complexité **n** d'un côté et **2n** de l'autre. C'est du même ordre de grandeur mais tu t'infliges un parcours qui au final ne t'apporte rien. Même si en lisant le code on peut penser que c'est une solution efficace, au final elle l'est moins.

**Comment by emilieDelsol** [comment]
Merci pour tes explications, c'est vrai qu'a première vue ça me parraissait être une bonne solution.. :) 
Il faut que je m'efforce à réfléchir à la complexité de mes algorithmes 👍

**Comment by cegerard** [comment]
@emilieDelsol En fait ton idée de départ est bonne. Prendre le tableau à l'envers et s'arrêter au premier élément qui match. Mais réécrire tout le tableau est très couteux.

En revanche un tableau c'est une structure contiguë en mémoire et tu peux très facilement le parcourir dans les deux sens.
Conclusion ton idée de départ est la bonne mais son implémentation n'était pas idéale.
