### ISSUE TITLE
erreur d'indice

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#3]
https://github.com/emilieDelsol/MentoratD2velop/blob/ed72dfe1e2c67bc7201c01a0b7e5883c49ef6826/searchJson/script.js#L30

Si je veux le nième élément d'un tableau dont les indices commences par 0 alors il faut récupérer l'élèment à l'indice n-1.

**Comment by emilieDelsol** [comment]
Exact! Je corrige immédiatement
