### ISSUE TITLE
Pourquoi une conversion ?

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#40]
https://github.com/emilieDelsol/MentoratD2velop/blob/4b9c57c7c200d4220aae098d3f85ce71d37c7cc1/searchJson/scriptEx2.js#L11

Je ne comprends pas pourquoi tu fais une convertion des labels ?
D'autant que j'ai mis "one", "two", etc. mais si le label c'est toto tu fais comment ?

**Comment by emilieDelsol** [comment]
exact si le label est toto ma convertion ne fonctionne plus .. Dans ce cas je ne sais pas comment les trier par rapport au label , je peux comparer des chaines de caractères mais je ne sais pas quel critère choisir

**Comment by cegerard** [comment]
Tu peux comparer des chaines de caractères comme des entier avec une simple === cela ne pause aucun problème.
C'est l'ordre lexicographique qui sera appliqué dans ce cas.

**Comment by emilieDelsol** [comment]
ok, c'est ce que j'avais fait au début mais j'ai ajouté la conversion pour les classer dans l'ordre croissant
