### ISSUE TITLE
comparaison manquante

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#42]
https://github.com/emilieDelsol/MentoratD2velop/blob/4b9c57c7c200d4220aae098d3f85ce71d37c7cc1/searchJson/scriptEx2.js#L46

Attention ici, tu as sois une, soit deux comparaison en fonction des cas.

**Comment by emilieDelsol** [comment]
ok, au début j'avais fait un 
`if(data[i].weight => data[i + 1].weight)`
`{`
`         comparaison++;`
`    if(data[i].weight === data[i+1].weight && labeli > labeliPlus1)`
`    {`
`        comparaison++;`
`        let temp = data[i + 1];`
`        data[i + 1] = data[i];`
`        data[i] = temp;`
`    }`
`    else`
`    {

`        let temp = data[i + 1];`
`        data[i + 1] = data[i];`
`        data[i] = temp;`
`    }`
`}`
 `
Je trouvais que ça faisait beaucoup de répétition de code.. Je vais essayer de trouver une solution :)
