### ISSUE TITLE
condition complexe

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#46]
https://github.com/emilieDelsol/MentoratD2velop/blob/7a220b9b74d0d20f10c919f89f3895cc945f7665/searchJson/scriptEx2.js#L15

Quand tu as des conditions de ce genre. Reponse au QCM sur l'algèbre de bool et dis toi que celui qui devra reprendre ton code devra également reproduire la même gymnastique mental pour bien comprendre ce que tu souhaites faire.

Il est préférable de deplacer les comparaisons dans des fonctions. Cela simplifie ton code et le rends plus lisible en mettant des noms explicites. Cela permet également de réutiliser le code pour d'autres comparaisons. Tu peux par exemple sortir une fonction ou deux fonction, une pour chaque partie du ||.

**Comment by emilieDelsol** [comment]
ok merci  :) je vais faire ça :)
