### ISSUE TITLE
tableau intermédiaire superflu

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#5]
https://github.com/emilieDelsol/MentoratD2velop/blob/ed72dfe1e2c67bc7201c01a0b7e5883c49ef6826/searchJson/script.js#L45

Pourquoi sotckquer tous les éléments dans un tableau pour à la fin récupérer le dernier. Tu peux simplement utiliser une variable et la remplacer à chaque fois que tu trouves un nouvel élément qui correspond. A la fin tu as forcément le dernier.

**Comment by emilieDelsol** [comment]
il faut que je pense plus à la complexité algorithmique quand je code ^^
