### ISSUE TITLE
fonction peu lisible

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#61]
https://github.com/emilieDelsol/MentoratD2velop/blob/b77a4ec80d53126d9dc4541799258a12c4d17b2a/searchJson/scriptFusionSort.js#L10

Cette fonction et trop longue. Il y a beaucoup de boucle avec des variables d'indice.
Même toi je suis sur que dans quelques temps, si tu veux reprendre ce code, tu auras du mal à le comprendre.

Je te conseil de le découper le plus possible. Il faut identifier les blocs de code qui peuvent être extrait dans une fonctione à part et normmer celle-ci pour décrire l'étape qu'elle représente dans l'algorithme.

**Comment by emilieDelsol** [comment]
ok super merci ! Je t'avoue que ça m'a demandé beaucoup d'effort pour comprendre le pseudo code duquel je suis partie pour écrire cette fonction ^^

**Comment by cegerard** [comment]
Pas de problème et c'est normal. C'est d'ailleurs comme qu'on fonctionne en générale on pose déjà quelque chose qui fonctionne de manière assez brut. Mais ensuite bien que cela fonctionne il ne faut pas s'en contenter. On prends le temps de reprendre le code et d'en faire quelque chose de lisible et propre, c'est ce qu'on appel la phase de refactoring. On verra ça plus en détail avec le TDD.
