### ISSUE TITLE
value ?

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#83]
https://github.com/emilieDelsol/MentoratD2velop/blob/766027c59a7267a31b99711060f8172251f8da65/ChainList/ChainList/ElementList.cs#L9

C'est le champ pour le poid celui là ?

**Comment by emilieDelsol** [comment]
Oui c'est celui pour le poids... J'aurais pu mettre Weight au lieu de value ^^ 
A début je voulais mettre Key pour Weight  et value pour label en m'inspirant du nommage des dictionnaires c# 
Je vais le modifier ^^

**Comment by cegerard** [comment]
Oui il faut utiliser un nom qui fait sens pour ton problème.

**Comment by emilieDelsol** [comment]
je le modifie partout ^^
