### ISSUE TITLE
Constructeur

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#84]
https://github.com/emilieDelsol/MentoratD2velop/blob/766027c59a7267a31b99711060f8172251f8da65/ChainList/ChainList/ElementList.cs#L18

Pourquoi un deuxième constructeur ?
Tu peux passer null comme dernier paramètre dans le premier et ça fait la même chose non ?

**Comment by emilieDelsol** [comment]
Oui c'est vrai, ça fait la même chose ça ne me plaisait pas de mettre null dans la parenthèse mais c'est vrai que ça fait du code en double qui fait exactement la même chose ^^
