### ISSUE TITLE
Encapsulation non respectée

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#87]
https://github.com/emilieDelsol/MentoratD2velop/blob/5468dae207f134a025a661fe1c4722111e07d7d9/ChainList/ChainList/ElementList.cs#L19

Pourquoi as-tu ajoutée tous ces accesseurs ?

**Comment by emilieDelsol** [comment]
Premiere raison: parce que le cours que j'ai trouvé sur Java le faisait comme ça . 
Mais ça ne m'a pas choqué car notre formateur nous a dit de toujours mettre les attributs en privé. 
Du coup il faut des accesseur pour modifier les valeurs. 
Mais vu que tu me poses la question c'est qu'il ne faut pas faire comme ça ^^ 
J'aurais dû mettre: protected int Weight {get; set; }

**Comment by cegerard** [comment]
Non en fait Hervé à fait la même chose et je me rends compte que vous n'avez pas vraiment de notion de programmation orientée objet...

**Comment by cegerard** [comment]
En fait en programmation orienté objet, il existe un principe fondamental qu'on appelle l'encapsulation.
Ca veut dire qu'on objet doit masquer son implémentation et ne jamais exposer ses attributs à l'extérieur.

Donc bien évidemment il ne faut pas déclarer les attributs "public" mais il ne faut pas non plus les exposer au moyen de getter et setter. Ton objet encapsule sont fonctionnement et tu ne dois pas lui demander la valeur de tel ou tel attribut ni même avoir à changer une valeur directement.

C'est un autre principe de la programmation orienté objet "Tell, don't ask".
