### ISSUE TITLE
public ou private

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#92]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/ChainList.cs#L9

Tu es obligée de le mettre public pour avoir les getter et les setter ?
Dans le cas contraire il faut le garder privé.

**Comment by emilieDelsol** [comment]
Si je le met en privé il faut que je crée un accesseur pour pouvoir accéder à sa valeur en dehors de la classe

**Comment by cegerard** [comment]
ok dac c'est la syntaxe C# du coup.

**Comment by emilieDelsol** [comment]
Le formateur nous faisait mettre {get; set;} sur les attributs qu'ils soient public ou privés, en fait à la création de l'attribut avec les raccourcis visual studio, en écrivant "prop et 2 fois tabulation" l'IDE écrit automatiquement les attributs avec {get;set;} et nous propose de modifier le type et le nom . si il n'y a rien devant, les attributs sont par défaut privés

**Comment by cegerard** [comment]
Ok, j'avoue ne pas maitriser la syntaxe C#.
Pour moi si tu as un attribut dans ta classe il est accessible dans ton instance que tu ais des get/set ou pas.
Mais c'est peut être pas la cas pour C# du coup.
