### ISSUE TITLE
visibilité

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#94]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/ElementList.cs#L8

Conserve tout tes attribut en privée.
Et ne le expose pas au moyen de getter et setter.
En fait il est très rare voir mais jamais necessaire d'accéder au attribut d'un objet.
A la place il préférable que l'objet expose une methode qui réponde au besoin extérieur.

Par exemple si tu as besoin de savoir si deux élement sont égaux. Tu ne dois pas accéder au différents attributs pour les comparer un à un. Cela va lier le code qui utilise l'élément à l'implémentation de l'élément et aura pour conséquence de te faire beaucoup de modifications quand tu fera évoluer ton élément.

La bonne solution c'est d'ajouter une méthode dans l'élément qui permet de faire cette comparaison ou de surcharger l'opzrateur == dans le cas de l'égualité.

**Comment by emilieDelsol** [comment]
ok :)
