### ISSUE TITLE
Compléxité

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#96]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/ChainList.cs#L43

Tu as créée une classe pour représenter ta liste chainée.
Plutôt que de parcourir ta liste à chaque fois pour aller trouver le dernière élément, tu pourrai garder la référence à cette élément.
Tout comme tu as start (on l'appelle head dans le cas d'une liste) tu pourrais avoir tail.

Si tu regardes ton initialisation où tu itères sur chaque élément extrait du json pour l'ajouté le gain est phénoménal car tu n'aurai auncun parcours. Essaye de te représenter la compléxité dans ton main de l'initialisation de la liste, un indice en c'est une de plus grande qu'on puisse faire.

**Comment by emilieDelsol** [comment]
O(n^2) ? :)

**Comment by cegerard** [comment]
Non O(n²) c'est pas très grave. C'est le point à partir duquel il faut se poser des questions.
Ici tu es en n!, c'est à dire une complexité exponentielle.

D'ailleurs en testant sur le tableau d'un 1M tu n'as pas sentie une différence à l'init avec les autres tableaux ?

**Comment by emilieDelsol** [comment]
Si c'est vrai que ça a été très long avec le tableau 1M , depuis mes dernières modifs c'est bien mieux ^^
