### ISSUE TITLE
variable ?

### ISSUE THREAD

**Issue by cegerard** [emilieDelsol/MentoratD2velop#99]
https://github.com/emilieDelsol/MentoratD2velop/blob/6ed1fbd778661fe890a7caadf03cf546e3c1f500/ChainList/ChainList/Program.cs#L44

A quoi sert cette variable ?

**Comment by emilieDelsol** [comment]
ligne 50 sa valeur devient currentElement (flag) , je trouvait bizarre de modifier la valeur de chainList.start dans la boucle while .

**Comment by cegerard** [comment]
Oui mais tu ne t'en sers jamais. Du coup elle inutile au final. C'est flag que tu utilises partout

**Comment by emilieDelsol** [comment]
exact, je l'ai supprimé :)  j'aurais pu le voir, l'ide colore différemment les variables non utiliséees... ;)
